START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob1','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','1');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob2','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','2');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob3','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','3');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob4','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','4');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob5','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','5');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob6','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','6');
COMMIT;
START TRANSACTION;
INSERT INTO users(username,password,email,phone,status,role) VALUES ('bob7','$2a$10$dio7TX4zmZrvRoUbiye.Sup65rQCGzCdT9ZrNGiu5bxE3pO3/TW66','pes@sobaka.net','8912344','true','ROLE_USER');
INSERT INTO passports(info,number) VALUES ('info','7');
COMMIT;